# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UsingSnapKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UsingSnapKit
  pod 'SnapKit', '~> 5.0.1'

  target 'UsingSnapKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UsingSnapKitUITests' do
    # Pods for testing
  end

end
